django Advance/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
admin.site.site_header = 'jamsproperty.com'
admin.site.site_title='jamsproperty.com'
admin.site.index_title = 'jamsproperty.com Adminstration'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(),name='index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS

]

django Advance/advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic App'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete')

]

django Advance/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principa = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    slug = models.SlugField(max_length=100, default=0)
    is_valid = models.BooleanField(default=0)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    last_modified = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE, )

    def __str__(self):
        return self.name

django Advance/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models
from django.urls import reverse_lazy


# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BSIC INJECTION'
        return context


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'basic_app/school_list.html'


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    template_name = 'basic_app/school_confirm_delete.html'
    success_url = reverse_lazy("basic_app:list")

django Advance/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" >Disabled</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
{% block body_block %}

{% endblock %}
</div>

</body>
</html>

django Advance/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <h1>Delete {{ school.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

django Advance/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <div class="jumbotron">
    <h1>Welcome to the school details page</h1>
    <h2>School details:</h2>
    <p>Name:{{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location:{{ school_detail.location }}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
        <p>{{ student.name }} who is {{ student.age }} years old</p>
    {% endfor %}
    </div>
<div class="container">
<p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

django Advance/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>
    <div class="jumbotron">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
    </div>

{% endblock %}

django Advance/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
   <div class="jumbotron">
   <h1>Welcome to list of all school</h1>
   <ol>
       {% for school in schools %}
       <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
       {% endfor %}
   </ol>
   </div>
{% endblock %}

django Advance/advcbv/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" >Disabled</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
{% block body_block %}

{% endblock %}
</div>

</body>
</html>

django Advance/advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
   <div class="jumbotron">
   <h1>Home Page</h1>
   </div>
{% endblock %}